# Generated by Django 4.2.23 on 2025-06-22 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_carouselslide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_slides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
