# Generated by Django 4.2.23 on 2025-06-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_carouselslide_author_carouselslide_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_views', to='news.carouselslide')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['slide', '-viewed_at'], name='news_slidev_slide_i_77a320_idx'), models.Index(fields=['ip_address', '-viewed_at'], name='news_slidev_ip_addr_367860_idx')],
            },
        ),
    ]
