# Generated by Django 4.2.23 on 2025-08-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_comment_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_video',
            field=models.FileField(blank=True, help_text='Featured video for the post', null=True, upload_to='blog/videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_video_post',
            field=models.BooleanField(default=False, help_text='Mark if this post is primarily a video post'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail for video', null=True, upload_to='blog/videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1920x1080', max_length=20)),
                ('format', models.CharField(blank=True, help_text='e.g., MP4, WebM', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('external_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL')),
                ('embed_code', models.TextField(blank=True, help_text='HTML embed code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
