# Generated by Django 4.2.23 on 2025-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_carouselslide_image_alter_post_featured_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_status_3180b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_categor_33f005_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_author__baa371_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='news_post_views_9ed7fc_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'created_at'], name='news_post_status_ee9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status'], name='news_post_categor_da046a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status'], name='news_post_author__fbe7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_trending', 'created_at'], name='news_post_is_tren_86bba5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_video_post', 'created_at'], name='news_post_is_vide_24dd1c_idx'),
        ),
    ]
