# Generated by Django 4.2.23 on 2026-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_post_news_post_status_3180b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_aggregated',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this post was auto-scraped'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, help_text='Name of the original source (e.g. Punch Nigeria)', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to original article if scraped', max_length=500),
        ),
    ]
