# Generated by Django 4.2.23 on 2026-03-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_post_is_aggregated_post_source_name_post_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_slide', to='news.post'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='scraped_image_url',
            field=models.URLField(blank=True, help_text='Stored URL for scraped posts (bypasses Cloudinary upload)', max_length=500, null=True),
        ),
    ]
