# Generated by Django 4.2.23 on 2026-03-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0010_post_is_aggregated_post_source_name_post_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Punch Nigeria', max_length=100)),
                ('site_url', models.URLField(help_text='Homepage URL of the source')),
                ('rss_url', models.URLField(help_text='Direct URL to the RSS feed', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop fetching from this feed')),
                ('is_featured', models.BooleanField(default=False, help_text='If checked, scraped posts will also be added to the Homepage Carousel')),
                ('fetch_interval', models.PositiveIntegerField(default=60, help_text='Minimum minutes between fetches')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(help_text='Category to assign to scraped posts by default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_sources', to='news.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('original_title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('error_log', models.TextField(blank=True, help_text='Error details if fetching/parsing failed')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_from', to='news.post')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_articles', to='scraper.newssource')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
